//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int FacilityID { get; set; }
        public string FacilityName { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
