//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int RequestID { get; set; }
        public string ModuleID { get; set; }
        public string Status { get; set; }
        public Nullable<int> StudentsReq { get; set; }
        public int Semester { get; set; }
        public Nullable<int> Weeks { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Periods { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SpecialReq { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
